In [4]:
import numpy as np
score=np.random.randint(0,101, size=50)
print("original score:/n",score)
mean_score = np.mean(score)
median_score = np.median(score)
highest_score = np.max(score)
lowest_score = np.min(score)
std_dev = np.std(score)

print(f"Mean Score:    {mean_score:.2f}")
print(f"Median Score:  {median_score:.1f}")
print(f"Highest Score: {highest_score}")
print(f"Lowest Score:  {lowest_score}")
print(f"Standard Deviation: {std_dev:.2f}")
fail_mask = score < 40
distinction_mask = score > 85

failing_scores = score[fail_mask]
distinction_scores = score[distinction_mask]

print(f"Number of failures: {len(failing_scores)} -> Scores: {failing_scores}")
print(f"Number of distinctions: {len(distinction_scores)} -> Scores: {distinction_scores}")



original score:/n [58 72 47 90 22 68 10  8 99  9 14 36 99 46  8 71 92 55  8 21 90 46 13  7
 83 36 37 44 78 98 55 27 59  2 93 91 23 95 54 45 98 70 94  5 12 52 11 63
 48 26]
Mean Score:    49.76
Median Score:  47.5
Highest Score: 99
Lowest Score:  2
Standard Deviation: 31.71
Number of failures: 20 -> Scores: [22 10  8  9 14 36  8  8 21 13  7 36 37 27  2 23  5 12 11 26]
Number of distinctions: 11 -> Scores: [90 99 99 92 90 98 93 91 95 98 94]


In [5]:
#normalize
normalized_scores = (score - lowest_score) / (highest_score - lowest_score)

print("First 10 Normalized Scores:\n", normalized_scores[:10])

First 10 Normalized Scores:
 [0.57731959 0.72164948 0.46391753 0.90721649 0.20618557 0.68041237
 0.08247423 0.06185567 1.         0.07216495]


In [6]:
# (5 subjects, 10 students per subject)
reshaped_scores = score.reshape(5, 10)

subject_averages = np.mean(reshaped_scores, axis=1)

print("Reshaped 5x10 Array:\n", reshaped_scores)
print("\nRow-wise (Subject) Averages:")

Reshaped 5x10 Array:
 [[58 72 47 90 22 68 10  8 99  9]
 [14 36 99 46  8 71 92 55  8 21]
 [90 46 13  7 83 36 37 44 78 98]
 [55 27 59  2 93 91 23 95 54 45]
 [98 70 94  5 12 52 11 63 48 26]]

Row-wise (Subject) Averages:


In [7]:
for i, avg in enumerate(subject_averages, start=1):
    print(f"Subject {i}: {avg:.2f}")

Subject 1: 48.30
Subject 2: 45.00
Subject 3: 53.20
Subject 4: 54.40
Subject 5: 47.90
